
module Main
import Control.Exception
import System.IO.Console
where

-- Test exception handler throwing an exception.
main ()
 = try (box error "not likely")
 $ \ex -> case ex of
                ExceptionError msg
                  -> error "it's still broken"
                _ -> writel $ "failed for some other reason"
